In [6]:
import numpy as np
import pandas as pd


class connect_x:
    
    def __init__(self):
        self.board_height  = 6 
        self.board_width = 7 
        self.board_state = np.zeros([self.board_height, self.board_width], dtype=np.int8)
        self.players = {'p1': 1, 'p2': 2}
        self.isDone = False
        self.reward = {'win': 1, 'draw': 0.5, 'lose': -1}
    
    #Status show the board  with Xs and Os
    def status(self):
        status_board = self.board_state.copy().astye(np.str)
        status_board[self.board_state == 0] = ' '
        status_board[self.board_state == 1] = 'O'
        status_board[self.board_state == 2] = 'X'
        display(pd.DataFrame(status_board))
        
    # Want the game to reset
    def reset(self):
        self.__init__()
        
    #check who won the game
    def check_winner(self, players):
        if players == 'p1':
            check = '1 1 1 1'
        else:
            check = '2 2 2 2'
        
        
    
    

In [6]:
board = connect_x().board_state 

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]], dtype=int8)

In [10]:
connect_x().board_state[5][0] = 1

In [11]:
connect_x().board_state[5]

array([0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [16]:
board = connect_x().board_state

In [17]:
board[5][0] = 1


In [18]:
board

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0]], dtype=int8)

In [ ]:
## Write out a dictionay or while look that 
#Make up a system but needs to be a string
#Coordinates system
# Make sure the AI can play the game. 